#!/usr/bin/env python3
"""
make_mozdzen_spectrum.py
------------------------
Generate a CSV spectrum from the Mozdzen et al. (2019) EDGES low-band
foreground model (MNRAS 483, 4416), equation 5: a 3-parameter power law
with a first-order ionospheric absorption term.

    T_ant(nu) = T75 * (nu/nu75)^(beta + gamma*ln(nu/nu75))
                     * (1 - tau * (nu/nu75)^-2) + T_CMB

Parameters are taken from Table 3 (3-parameter fit, with ionospheric
correction). By default we emit the LST = 6h pointing, which samples the
coldest sky (Galaxy set) and is the fairest single-pointing comparison to
the pole-directed historical measurements.

The paper's fit is only constrained over 50-100 MHz; requesting frequencies
outside that range extrapolates the model and triggers a warning.

Usage:
    python make_mozdzen_spectrum.py --fmin 50 --fmax 100 --resolution 0.5 \
        --output mozdzen2019_lst6_spectrum.csv
"""

import argparse
import sys
import numpy as np

# ── Model parameters (Mozdzen+ 2019, Table 3, 3-param + ionosphere) ──────────
# Each entry: (T75_K, beta, gamma) at a representative LST.
MOZDZEN_LST_PARAMS = {
    0:  (1816.0, -2.603, -0.042),
    6:  (1682.0, -2.595, -0.034),
    12: (2580.0, -2.578, -0.086),
    18: (4776.0, -2.499, -0.076),
}
TAU   = 0.005          # fixed night-time ionospheric absorption coefficient
NU0   = 75.0           # MHz, reference frequency
T_CMB = 2.725          # K

# Frequency range over which the paper's fit is valid
PAPER_FMIN = 50.0      # MHz
PAPER_FMAX = 100.0     # MHz


def mozdzen_T(nu_MHz, T75, beta, gamma, tau=TAU):
    """Mozdzen+ 2019 eq. 5: 3-param power law with ionospheric absorption."""
    x = np.asarray(nu_MHz, dtype=float) / NU0
    return T75 * x**(beta + gamma * np.log(x)) * (1.0 - tau * x**(-2)) + T_CMB


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--fmin', type=float, default=50.0,
                   help='Minimum frequency in MHz (default 50)')
    p.add_argument('--fmax', type=float, default=100.0,
                   help='Maximum frequency in MHz (default 100)')
    p.add_argument('--resolution', type=float, default=0.5,
                   help='Frequency step in MHz (default 0.5)')
    p.add_argument('--lst', type=int, default=6, choices=sorted(MOZDZEN_LST_PARAMS),
                   help='LST hour to emit (default 6 = coldest sky)')
    p.add_argument('--output', default='mozdzen2019_lst6_spectrum.csv',
                   help='Output CSV path')
    args = p.parse_args()

    if args.fmin >= args.fmax:
        sys.exit(f"Error: fmin ({args.fmin}) must be < fmax ({args.fmax})")

    # Warn on extrapolation beyond the paper's fitted range
    if args.fmin < PAPER_FMIN or args.fmax > PAPER_FMAX:
        print(f"WARNING: requested range {args.fmin}-{args.fmax} MHz extends "
              f"beyond the Mozdzen+ 2019 fitted range of "
              f"{PAPER_FMIN}-{PAPER_FMAX} MHz.", file=sys.stderr)
        print("         Values outside 50-100 MHz are extrapolations of the "
              "model and are not constrained by the data.", file=sys.stderr)

    T75, beta, gamma = MOZDZEN_LST_PARAMS[args.lst]

    nu = np.arange(args.fmin, args.fmax + args.resolution / 2, args.resolution)
    T  = mozdzen_T(nu, T75, beta, gamma)

    with open(args.output, 'w') as f:
        f.write("# Mozdzen et al. (2019) EDGES low-band foreground model\n")
        f.write("# Source: MNRAS 483, 4416-4423 (2019), eq. 5 + Table 3\n")
        f.write("# Model: 3-parameter power law with first-order ionospheric absorption\n")
        f.write(f"#   T_ant(nu) = T75*(nu/{NU0})^(beta+gamma*ln(nu/{NU0}))"
                f"*(1 - tau*(nu/{NU0})^-2) + T_CMB\n")
        f.write(f"# Parameters (LST={args.lst}h, 3-param + ionosphere): "
                f"T75={T75} K, beta={beta}, gamma={gamma}, tau={TAU}, T_CMB={T_CMB} K\n")
        f.write(f"# Valid (fitted) range: {PAPER_FMIN}-{PAPER_FMAX} MHz\n")
        f.write(f"# Generated range: {args.fmin}-{args.fmax} MHz at "
                f"{args.resolution} MHz resolution\n")
        if args.fmin < PAPER_FMIN or args.fmax > PAPER_FMAX:
            f.write("# NOTE: this file extends beyond the fitted range; "
                    "out-of-band points are extrapolations\n")
        f.write("# This is a MODEL curve, not measured data.\n")
        f.write("# CHANGELOG\n")
        f.write("# 2026-07-08: Generated by make_mozdzen_spectrum.py\n")
        f.write("#\n")
        f.write("frequency_MHz,T_antenna_K\n")
        for freq, temp in zip(nu, T):
            f.write(f"{freq:.4f},{temp:.4f}\n")

    print(f"Wrote {len(nu)} points to {args.output} "
          f"(LST={args.lst}h, {args.fmin}-{args.fmax} MHz)")


if __name__ == '__main__':
    main()
